#include <cerrno>
#include <csignal>
#include <ctime>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#ifndef _WIN32
#ifdef __APPLE__
#include <libproc.h>
#include <sys/proc.h>
#endif
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/un.h>
#include <unistd.h>
#endif

// Privileged helper.
//
// The GUI stays unprivileged; only this runs as root. That split is not just
// hygiene: the lock server has to live in the user's own interactive session,
// and every platform's lock API refuses to act on a session the caller is not
// part of. Relaunching the whole GUI as root would silently break it.
//
// **Why a socket rather than stdio.** The first design read commands from
// stdin, which cannot work here: macOS elevates via osascript, and osascript
// does not forward stdin to the child and only returns its output once the
// child exits. So the helper is launched detached by the elevation prompt and
// listens on a Unix socket instead. The user authenticates once; every
// privileged operation for the rest of the session goes over that socket
// without a further prompt.
//
// Security properties:
//
//  * The socket is owned by the user who launched the GUI and chmod 0600, so
//    only that user (and root) can connect. It cannot be 0700-root: the GUI
//    runs unprivileged and would be locked out of its own helper.
//  * That means the socket's owner is the trust boundary, and it is the same
//    boundary the rest of this design already relies on - anyone who can run
//    code as you can already drive the GUI, which can already elevate.
//  * A random token, generated by the parent and required as the first line
//    of every connection, guards against another process on the same account
//    stumbling into the socket. It is passed by environment rather than argv,
//    since argv is world-readable through ps.
//  * The helper exits when its parent dies, so it cannot outlive the GUI as
//    an idle root process, and an idle timeout bounds it even if that
//    detection ever fails.
//  * Commands are executed verbatim. There is deliberately no sanitising
//    layer: a filter would give false confidence when the actual guarantee is
//    that only root can reach the socket at all. Callers must never
//    interpolate untrusted input.
//
// Protocol, line-oriented, one connection per command:
//
//   -> <token>
//   -> RUN <shell command>
//   <- OUT <line>        (repeated)
//   <- EXIT <code>
//
// A connection presenting the wrong token is closed immediately.
namespace {

std::string g_Token{};
pid_t g_ParentPid = 0;
std::time_t g_LastActivity = 0;

// Hard ceiling on an idle root helper, in case parent detection ever fails.
constexpr std::time_t IDLE_TIMEOUT_SECS = 30 * 60;

// Whether the parent is genuinely running.
//
// kill(pid, 0) alone is wrong here: it succeeds for a zombie, so a helper
// relying on it outlives a parent that has exited but not been reaped.
bool IsParentAlive(pid_t pid) {
#ifdef __APPLE__
  proc_bsdinfo info{};
  auto n = proc_pidinfo(pid, PROC_PIDTBSDINFO, 0, &info, sizeof(info));
  if(n == static_cast<int>(sizeof(info)))
    return (info.pbi_status != SZOMB);
  // Lookup failed: the process is gone.
  return false;
#else
  // /proc is authoritative on Linux; state 'Z' means zombie.
  auto path = "/proc/" + std::to_string(pid) + "/stat";
  auto f = fopen(path.c_str(), "r");
  if(f == nullptr)
    return false;
  char comm[256]{};
  char state = 0;
  int readPid = 0;
  auto matched = fscanf(f, "%d %255s %c", &readPid, comm, &state);
  fclose(f);
  if(matched != 3)
    return false;
  return state != 'Z';
#endif
}

// Reads a newline-terminated line from a socket. Empty on EOF or error.
std::string ReadLine(int fd) {
  std::string line{};
  char c = 0;
  while(true) {
    auto n = read(fd, &c, 1);
    if(n <= 0)
      return line;
    if(c == '\n')
      return line;
    if(c != '\r')
      line += c;
    if(line.size() > 65536) // Refuse to buffer without bound.
      return line;
  }
}

void WriteLine(int fd, const std::string &line) {
  auto payload = line + "\n";
  auto remaining = payload.size();
  auto p = payload.c_str();
  while(remaining > 0) {
    auto n = write(fd, p, remaining);
    if(n <= 0)
      return;
    p += n;
    remaining -= static_cast<size_t>(n);
  }
}

// Runs one command, streaming its output back line by line.
int RunCommand(int fd, const std::string &cmd) {
  auto pipe = popen(cmd.c_str(), "r");
  if(pipe == nullptr) {
    WriteLine(fd, "OUT failed to start command");
    return -1;
  }
  char buffer[4096];
  while(fgets(buffer, sizeof(buffer), pipe) != nullptr) {
    std::string line(buffer);
    while(!line.empty() && (line.back() == '\n' || line.back() == '\r'))
      line.pop_back();
    WriteLine(fd, "OUT " + line);
  }
  auto status = pclose(pipe);
  if(status == -1)
    return -1;
  return WIFEXITED(status) ? WEXITSTATUS(status) : -1;
}

void HandleConnection(int fd) {
  // First line must be the token, or the peer is not our parent.
  auto token = ReadLine(fd);
  if(token != g_Token) {
    WriteLine(fd, "EXIT -1");
    return;
  }
  auto line = ReadLine(fd);
  if(line.rfind("RUN ", 0) != 0) {
    WriteLine(fd, "EXIT -1");
    return;
  }
  auto code = RunCommand(fd, line.substr(4));
  WriteLine(fd, "EXIT " + std::to_string(code));
}

} // namespace

int main(int argc, char *argv[]) {
  setvbuf(stdout, nullptr, _IONBF, 0);

  // A client that closes mid-reply would otherwise raise SIGPIPE and kill the
  // helper, taking the whole privileged session with it after a single
  // command. Writes return EPIPE instead, which the write loop already
  // handles.
  signal(SIGPIPE, SIG_IGN);

  if(argc != 4) {
    fprintf(stderr, "usage: pcbu_elevator <socket-path> <owner-uid> <parent-pid>\n");
    return 2;
  }
  std::string socketPath = argv[1];
  auto ownerUid = static_cast<uid_t>(std::atoi(argv[2]));
  g_ParentPid = static_cast<pid_t>(std::atoi(argv[3]));

  // Token by environment, not argv: argv is visible to every user via ps.
  if(auto env = getenv("PCBU_ELEVATOR_TOKEN"); env != nullptr) {
    g_Token = env;
    unsetenv("PCBU_ELEVATOR_TOKEN");
  }
  if(g_Token.empty()) {
    fprintf(stderr, "missing token\n");
    return 1;
  }

  if(geteuid() != 0) {
    fprintf(stderr, "not running as root\n");
    return 1;
  }
  if(socketPath.size() >= sizeof(sockaddr_un::sun_path)) {
    fprintf(stderr, "socket path too long\n");
    return 1;
  }

  // The directory is owned by the launching user, mode 0700, so no other
  // account can reach the socket inode. Root-owned would lock out the very
  // process that needs to connect.
  auto slash = socketPath.find_last_of('/');
  if(slash != std::string::npos) {
    auto dir = socketPath.substr(0, slash);
    mkdir(dir.c_str(), 0700);
    chmod(dir.c_str(), 0700);
    chown(dir.c_str(), ownerUid, static_cast<gid_t>(-1));
  }
  unlink(socketPath.c_str());

  auto server = socket(AF_UNIX, SOCK_STREAM, 0);
  if(server < 0) {
    fprintf(stderr, "socket() failed: %s\n", strerror(errno));
    return 1;
  }
  sockaddr_un addr{};
  addr.sun_family = AF_UNIX;
  std::strncpy(addr.sun_path, socketPath.c_str(), sizeof(addr.sun_path) - 1);
  if(bind(server, reinterpret_cast<sockaddr *>(&addr), sizeof(addr)) < 0) {
    fprintf(stderr, "bind() failed: %s\n", strerror(errno));
    close(server);
    return 1;
  }
  // Hand the socket to the launching user so the unprivileged GUI can connect.
  chown(socketPath.c_str(), ownerUid, static_cast<gid_t>(-1));
  chmod(socketPath.c_str(), 0600);
  if(listen(server, 4) < 0) {
    fprintf(stderr, "listen() failed: %s\n", strerror(errno));
    close(server);
    return 1;
  }

  // select() with a timeout, not SO_RCVTIMEO: that option does not apply to
  // accept() on a listening socket, so the loop blocked forever and the
  // parent-liveness check never ran. Verified - the helper outlived a dead
  // parent until this was fixed.

  g_LastActivity = std::time(nullptr);
  printf("READY\n");
  fflush(stdout);

  while(true) {
    // Never outlive the GUI: an abandoned root listener is exactly the thing
    // this design must not leave behind.
    //
    // kill(pid, 0) is not sufficient on its own. It succeeds for a zombie -
    // a dead process that has not been reaped - so a helper checking only
    // that would linger indefinitely. Verified: with a killed-but-unreaped
    // parent, the kill() check never fired.
    //
    // proc_pidinfo tells us whether the process is really running. Falling
    // back to kill() elsewhere keeps this portable; the idle timeout below
    // bounds the damage either way.
    if(!IsParentAlive(g_ParentPid))
      break;

    // Belt and braces: even if parent detection fails on some platform, an
    // idle helper must not live forever. Any successful command resets this.
    if(std::time(nullptr) - g_LastActivity > IDLE_TIMEOUT_SECS) {
      fprintf(stderr, "idle timeout; exiting\n");
      break;
    }

    // Wait with a timeout so the checks above run even while idle.
    fd_set readSet;
    FD_ZERO(&readSet);
    FD_SET(server, &readSet);
    timeval timeout{};
    timeout.tv_sec = 2;
    timeout.tv_usec = 0;
    auto ready = select(server + 1, &readSet, nullptr, nullptr, &timeout);
    if(ready == 0)
      continue; // Idle tick: loop back and re-check the parent.
    if(ready < 0) {
      if(errno == EINTR)
        continue;
      break;
    }

    auto client = accept(server, nullptr, nullptr);
    if(client < 0) {
      if(errno == EAGAIN || errno == EWOULDBLOCK || errno == EINTR)
        continue;
      break;
    }
    HandleConnection(client);
    close(client);
    g_LastActivity = std::time(nullptr);
  }

  close(server);
  unlink(socketPath.c_str());
  return 0;
}
